import "~/styles/globals.css";
import { SignIn } from "./_components/sign-in";
import { SignOut } from "./_components/sign-out";

import { auth } from "~/server/auth";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  console.log("session", session);
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          {!session ? <SignIn /> : <SignOut />}
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
